language: php

php:
    - 7.3
    - 8.0
    - 8.2

env:
    matrix:
        - COMPOSER_FLAGS="--prefer-lowest"
        - COMPOSER_FLAGS=""

before_script:
- travis_retry composer self-update
- travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source
- export XDEBUG_MODE=coverage

script:
  - vendor/bin/phpunit